GRID_ROWS = 6 
GRID_COLS = 5

WINDOW_WIDTH = 660
WINDOW_HEIGHT = 650
WINDOW_TITLE = "Wordle Remastered"

API_URL = "https://localhost:7229"
GET_OPENER_ENDPOINT = "/opener"
GET_NEXT_GUESS_ENDPOINT = "/next-guess"