DEFAULT_WORD = "STATS"

GRID_ROWS = 6 
GRID_COLS = 5

WINDOW_WON_DIALOG_TITLE = "Game Won"
WINDOW_WON_DIALOG_WIDTH = 175
WINDOW_WON_DIALOG_HEIGHT = 140

WINDOW_WIDTH = 660
WINDOW_HEIGHT = 650
WINDOW_TITLE = "Wordle Solver"

API_URL = "https://localhost:59708"
GET_OPENER_ENDPOINT = "/opener"
GET_NEXT_GUESS_ENDPOINT = "/guesses/next-guess"